Makefile, java8/Dockerfile
`libmaven2-core-java` depends on `libdoxia-java`, which depends on `libfop-java`, which depends on `libxt6`, which depends on `libx11-6`, which shouldn't be removed.
Fixes #10
=> Avoid purging Maven via its dependencies

java8/Dockerfile, node4.6/Dockerfile, node6.9/Dockerfile, node7.0/Dockerfile, php5.6/Dockerfile, php7.0/Dockerfile
Removing `/var/lib/dpkg/info` prevents `dpkg` and APT from functioning correctly.
Also, `composer` in the PHP images depends on the PostgreSQL lib (`libpq5`) but not as a deb dependency, so in order to keep the `apt-get autoremove` step, the `postgresql-client` is installed.
=> Remove a bit less elements to keep the images functional

java8/Dockerfile, node4.6/Dockerfile, node6.9/Dockerfile, node7.0/Dockerfile, php5.6/Dockerfile, php7.0/Dockerfile
The JVM at least uses the encoding of the current locale, or an ANSI
encoding if none is set, which can give ugly results when displaying
non-ANSI characters.
=> Set up a locale with a UTF-8 encoding

CHANGELOG.md, node/Dockerfile
gcc and g++ are needed by some node dependencies. Having to install them manually on each build creates false negatives because of network issues and is generally inefficient.
=> Add gcc and g++ into Node image

dind-aws/Dockerfile
`gitlab/dind` was built a year ago and is outdated
=> fix(dind-aws): update base image to use dockerd instead of docker daemon

node/Dockerfile
Yarn automatically installs Node.js by default.
We can skip it by using `--no-install-recommends` as recommended by the [documentation](https://yarnpkg.com/lang/en/docs/install/) : 
> If using nvm you can avoid the node installation by doing:
`sudo apt-get install --no-install-recommends yarn`
=> Prevent Yarn from installing Node.js

CHANGELOG.md, README.md, aws/Dockerfile, dind-aws/Dockerfile, golang/Dockerfile, java/Dockerfile.tpl, node/Dockerfile, php/5.3/Dockerfile, php/Dockerfile.tpl, react-native/Dockerfile
The mime type of the files that are pushed in an AWS storage (and the `Content-Type` HTTP header sent for them) is defined by the [AWS CLI](https://github.com/aws/aws-cli) tool.
You can see [there](https://github.com/aws/aws-cli/blob/5d349108c974d80b5b1a634e8a7433556a31e605/awscli/customizations/s3/utils.py#L294) that the AWS CLI uses the [mimetypes](https://docs.python.org/2/library/mimetypes.html) core Python module to guess the mime types, based on the sender `/etc/mime.types` file.
As the buildboxes use Debian as their base OS, the provider of that file is the [mime-support](https://salsa.debian.org/debian/mime-support) Debian package. But in the current stable Debian version, the more up to date version of the package is 3.60, and the definition file is incomplete (eg: the woff2 mime …
=> Add an up to date mime types definition file for the images that use AWS CLI

.travis.yml, CHANGELOG.md, README.md, java/6/Dockerfile, travis.py
Creating a new buildbox to compile old code in Java 6, using a JDK from Sun / Oracle.
A Sun JDK 6 was found on old Debian distro : squeeze (6.0). 
Unfortunatly, this distro use an old version of openssl (0.98) which prevents using "curl" over HTTPS in most cases.
=> feat(java) add new buildbox using Sun JDK 6

CHANGELOG.md, python/Dockerfile.tpl
* Add `basic-build`, `libffi-dev` and `openldap-dev` packages as they are often needed to build dependencies
* Upgrade pip version
=> Python Images - Add basic packages to build C Python dependencies

CHANGELOG.md, java/Dockerfile.tpl, travis.py
Currently aws command return this error :
`Traceback (most recent call last):
File "/usr/local/bin/aws", line 19, in <module>
import awscli.clidriver
File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 17, in <module>
import botocore.session
File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 27, in <module>
import botocore.credentials
File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 27, in <module>
from dateutil.parser import parse
File "/usr/local/lib/python2.7/dist-packages/dateutil/parser/__init__.py", line 2, in <module>
from ._parser import parse, parser, parserinfo
File "/usr/local/lib/python2.7/dist-packages/dateutil/parser/_parser.py", line 42, in <module>
import six
ImportError: No module named six`
I remove the …
=> fix(java) : fix aws error ImportError: No module named six

.travis.yml, CHANGELOG.md
We encounter a problem using Maven 3.2.5 with old Linux distro (the one for Java 6 buildbox), as it uses HTTPS by default to connect to Maven Central. This one requires a recent version of TLS protocol, not present in the old Linux distro : that strikes errors like the one below.
```
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/maven-metadata.xml
[WARNING] Could not transfer metadata org.apache.maven.plugins:maven-compiler-plugin/maven-metadata.xml from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version
```
=> fix(java): downgrade maven version for java 6

CHANGELOG.md, java/Dockerfile.tpl
Error on build : 
```
Setting up openjdk-8-jre-headless:amd64 (8u212-b03-2~deb9u1) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: error: error creating symbolic link '/usr/share/man/man1/rmid.1.gz.dpkg-tmp': No such file or directory
dpkg: error processing package openjdk-8-jre-headless:amd64 (--configure):
```
Looks like this issue on debian stretch : https://github.com/debuerreotype/docker-debian-artifacts/issues/24
As described in the issue openjdk has previously had a fix for this, but it seems not reported on latest dockerfile ... I just copy/paste the fix in our image.
This is a quick fix, maybe in a next release we can move to adoptopenjdk sources that seems more stable ...
=> chore(java): fix java 8/11 images build

.travis.yml, CHANGELOG.md, ansible/Dockerfile, travis.py
Dockerfile re-arrangement for build passing. This is a quickfix for #172 to pass, this image will need to be upgrade to python 3.x and Ansible 2.7 at least.
=> Fix ansible 2.5.5 w/ python 2.7 image build

java/6/Dockerfile
TLS 1.2 is not supported on Debian Squeeze
=> fix(java): fix java 6 build by disabling ssl check on maven download

src/config.py, travis.py
Following docker pull issue management from #199, I ended managing TRAVIS_TAG value as a string which value was either "false" or "true".
As it is not how TRAVIS_TAG var works, I revert this change to manage as it should be: empty string if it is not a tag event, not empty if it is.
=> Fix TRAVIS_TAG env var management

CHANGELOG.md, chrome/Dockerfile
Hi,
Fix for https://github.com/ekino/docker-buildbox/issues/212
The Alpine version is now the one provided by the `node:10-alpine` base image. It makes it install Chrome 72 which is outdated but at least it won't broke randomly.
=> fix: Chrome image

CHANGELOG.md, config.yml
CVE-2019-16276 fix
https://groups.google.com/forum/#!msg/golang-announce/cszieYyuL9Q/g4Z7pKaqAgAJ
=> chore(security): upgrade golang version to 1.13.1

CHANGELOG.md, config.yml, node/Dockerfile
Hi,
I've also removed `mercurial` and `subversion` which aren't used very much these days.
=> chore: upgrade node images to debian 10.1

.gitignore, .travis.yml, CHANGELOG.md, config.yml
some fixes on golang https://github.com/golang/go/issues?q=milestone%3AGo1.13.4  
and a little upgrade for serveless
=> chore(upgrade): upgrade golang (1.13.4) and serverless (1.57)

.travis.yml, CHANGELOG.md, README.md, config.yml, react-native/Dockerfile
Hi there,
I did some small things in the React Native image:
* Upgrade Node.js from v7 to v12 (LTS)
* Remove Watchman
* Remove some exposed ports
* Remove the custom user because of issues with root-owned files (eg: cached dependencies from a previous CI job, based on another Docker image)
=> feat(react-native): upgrade Node/NPM and remove watchman, exposed ports and the custom user

CHANGELOG.md, README.md, config.yml, java/Dockerfile.j2
`psql` can be useful to add schemas/users/roles on a ci postgres service.
In `gitlab-ci` for example it's not possible to add an init script to a postgres service.
=> feat(java): add psql to java build image

CHANGELOG.md, README.md, config.yml, golang/Dockerfile.j2
- Glide is not used anymore since we use Go modules
- modd is now installed per project if needed
- Same for gin
Keep updated mime types because it add jsonld mime type
```bash
(docker-buildbox) ➜  docker-buildbox git:(chore/cleanup) orig=$(docker run  golang:1.13.6 bash -c "cat /etc/mime.types"); \                
up=$(curl https://salsa.debian.org/debian/mime-support/raw/master/mime.types); \
diff <(echo $orig) <(echo $up)
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 24546  100 24546    0     0  34091      0 --:--:-- --:--:-- --:--:-- 34044
75c75
< application/javascript                                js
---
> application/javascript                                js mjs
76a77
> application/ld+json …
```
=> chore(cleanup): remove unused Golang packages

.travis.yml, CHANGELOG.md, config.yml
Nodejs 8 has reached its EOL. IMO it's safe to stop supporting it.
=> chore: remove support for nodejs 8

.gitignore, .travis.yml, CHANGELOG.md, README.md, config.yml, ibm/Dockerfile.j2
Create image to deploy infra on IBM Cloud using Terraform 0.12, IBM terraform provider and IBM Cloud CLI.
=> Create image for IBM deployment

aws/Dockerfile.j2, config.yml
We discovered on ekino/ci-aws:latest that we cannot make troposphere diffs as it needs git and git isn't part of debian:buster-slim.
=> Add git in AWS Image

CHANGELOG.md, src/docker_image.py
Our CI is now faster, and we now have random timeouts when pushing to docker hub multiple times in parallel : https://github.com/ekino/docker-buildbox/runs/539228402?check_suite_focus=true
It seems to be a known issue : https://github.com/docker/docker-py/issues/2096
The default timeout is 60 seconds, and this commit will increase it to 600 seconds.
=> feat(docker): increase docker client timeout to 10 minutes

.github/workflows/build-checker.yml, CHANGELOG.md
Today, having one build per image configuration raises two issues:
* When we add a new configuration or remove an existing one, **a repository owner has to manually update the required checks** for merging a PR. See https://github.com/ekino/docker-buildbox/pull/274#issuecomment-609871057
* When we'll be able to build only the images that were modified, **the checks requirements won't be satisfied**. See https://github.com/ekino/docker-buildbox/pull/271#issuecomment-610286063
The goal of this PR is to create a new workflow whose one and only role is to check the statuses of every other jobs for the commit: Build Checker.
We will then be able to require only this check to succeed before merging, solving all our problems that way.
I used an action that does exactly that:
* Repository: …
=> feat(ci): create a single workflow for checking all the other statuses

.github/workflows/build.yml
According to a Github dev (https://github.com/actions/runner/issues/343#issuecomment-590634907), we can now directly use `include` to create new matrix entries like we did on Travis :tada:.
I also removed useless intermediate env variables and linted the matrix a bit to change the case and have a clean "column" look.
While we're at it : Do you prefer the "column style" or the "list style", or the previous style?
Column style (really easy to read, but awful to maintain):
```
strategy:
matrix:
include:
- { image: ansible, version: 2.9  }
- { image: aws    , version: 1    }
- { image: aws    , version: 2    }
- { image: aws    , version: 3    }
- { image: chrome , version: 1    }
- { image: dind   , version: 1    }
- { image: golang , version: 1.14 }
```
List style (not really easy to read, …
=> chore(ci): lint matrix and new include override

config.yml, tezosqa/Dockerfile.j2
Hello, Here is a little update to fix docker-buildbox builds, as the install script currently returns a not found error
=> fix(tezosqa): update smartpy install script url

.github/workflows/build-checker.yml
cc @Crow-EH 
Using v1 is supposed to resolve https://github.com/WyriHaximus/github-action-wait-for-status/issues/3
We currently have those kind of failures (see https://github.com/ekino/docker-buildbox/pull/309/checks?check_run_id=919006633 for example).
=> fix(ci): use v1 for WyriHaximus/github-action-wait-for-status

.github/workflows/build-checker.yml
Failing jobs are not detected by our build checker (the only job required to pass for merging any PR).
Upgrading wait-for-status to 1.2 fixes it: https://github.com/WyriHaximus/github-action-wait-for-status/issues/21
Here is a pull request reproducing the issue: https://github.com/Crow-EH/github-action-wait-for-status-issue-21/pull/1
And here is the same thing in v1.2: https://github.com/Crow-EH/github-action-wait-for-status-issue-21/pull/19
=> fix(check): failing jobs not detected

CHANGELOG.md, node/Dockerfile, react-native/Dockerfile
The current `node` image include the `awscli` in the build, however removing `python-pip` and `auto-remove` remove the python interpretor from the final image
```
docker run -ti --rm ekino/ci-node:12-2020.09.30 /bin/bash -c 'aws'                                               
/bin/bash: /usr/local/bin/aws: /usr/bin/python: bad interpreter: No such file or directory
```
This PR does not remove the `python-pip` so the python packages are not flagged to be deleted.
=> fix(awscli): make sure python is still present

CHANGELOG.md, config.yml
**Note:** version >= 3.0.0 does not support Taskfiles written for the first version anymore
https://taskfile.dev/#/taskfile_versions?id=version-1
=> feat: upgrade Taskfile to v3.2.2

.github/workflows/build.yml, matrix_generator.py
This allows making PR for excluded files only without building every images (see #524).
Also excludes dependabot config for #514.
The check that `include` has at least one item is because Github Actions will fail on empty matrixes (job's `if` is interpreded before matrix expansion).
Tests:
* https://github.com/Crow-EH/docker-buildbox/pull/2
* https://github.com/Crow-EH/docker-buildbox/pull/3
* https://github.com/Crow-EH/docker-buildbox/pull/4
Blocked by #523
=> ci(build): no build when all files excluded and exclude dependabot conf

README.md
New URL is cleaner IMO https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
=> docs(readme): use new actions badge url and fix link to include scheduled jobs

CHANGELOG.md, image_builder.py, src/docker_tools.py
Issues : 
* AWS : Fix lack of amd64 arch on docker hub
Issue origin :
The conventional docker retag/push strategy https://github.com/ekino/docker-buildbox/blob/master/image_builder.py#L55-L56 only keeps the image manifest for the architecture platform of the system from which I perform the retag/push (in this case arm64)
=> Aws build arm64 docker image

.github/dependabot.yml, CHANGELOG.md, php/8.0/Dockerfile, php/8.1/Dockerfile, php/8.2/Dockerfile, php/config.yml, php/run.sh
- Add `linux-headers` because of :
[configure: error: rtnetlink.h is required, install the linux-headers package: apk add --update linux-headers](https://github.com/vladsolntsev/docker-buildbox/actions/runs/3940339455/jobs/6741325494#step:7:5753)
that caused xdebug and blackfire to not install properly
- PHP 8.0 doesn't have any official image on Alpine 3.17, and different musl versions are needed on Alpine 3.16 and 3.17. 
- Everything builds for 8.2 but php-cs-fixer that isn't fully ready yet for 8.2 (https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6749). Set PHP_CS_FIXER_IGNORE_ENV to bypass the warnings.
=> chore(php): add php 8.2 image & remove 7.4

CHANGELOG.md, tezosqa/Dockerfile, tezosqa/config.yml
- Update smartpy and ligo installation process.
- Change the base image from python:3.8-slim-bullseye to docker:20.10.24-dind in order to be able to run docker inside the container. This is due to the fact that the new smartpy executable now needs docker to work. 
- Change apt by apk in order to be compatible with the new base image
- In the config.yml: change test configs, remove all env variables and configure the tezosqa image as being compatible with both amd64 and arm64 architectures
=> Fix tezosqa

CHANGELOG.md, dind/Dockerfile, dind/config.yml
**Improvements**
* Dind : build arm64 docker image
**Issue**
* aws: not found on arm64 
* The weird behavior that the install seems to fail at line 78 of the install script, but the install script seems to complete successfully, only to then fail when we try to actually run the installed bin. The bug discussion forum https://github.com/aws/aws-cli/issues/4971
=> [Dind] Feat : build arm64 docker image

CHANGELOG.md, azure/Dockerfile, azure/config.yml
Using `ekino/ci-azure:2-2024.10.31`:
```bash
$ tfenv install
Installing Terraform v1.9.8
Downloading release tarball from https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
######################################################################## 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_SHA256SUMS
Not instructed to use Local PGP (/root/.tfenv/use-{gpgv,gnupg}) & No keybase install found, skipping OpenPGP signature verification
/root/.tfenv/libexec/tfenv-install: line 297: unzip: command not found
Tarball unzip failed
```
=> Azure: installing zip to use tfenv
