node0.12/Dockerfile
node4.3/Dockerfile
node5.7/Dockerfile

https://github.com/brigade/scss-lint
Install ruby, sass and scss_lint

add ruby, sass and scss_lint tools

---

java8/Dockerfile

The removed parts mostly concern JavaFX.

Remove more unused parts of the JDK

---

.travis.yml
CHANGELOG.md
aws/Dockerfile
travis.py

The image provides an environment to manipulate an AWS stack, either with
the shell and awscli, or with a Python script: boto3 and PyYAML are already
installed, more dependencies can be installed via PIP.

Add an AWS image

---

.travis.yml
README.md
dind-aws/Dockerfile
travis.py

Fixes https://github.com/ekino/docker-dind-aws/issues/3

Add dind-aws image to this repo, and documentation

---

CHANGELOG.md
java/Dockerfile
node/Dockerfile
php/Dockerfile

Add bzip2 to Java Php and Node image

---

CHANGELOG.md
aws/Dockerfile

Add rsync and zip to the aws image

---

travis.py

👋 I was boring in the train, looking at your build box (cause I think I will use something like that) and here is this PR ;)
Hope everything is going well for you guys!

Fixed travis.py error messages

---

.travis.yml
CHANGELOG.md
chrome/Dockerfile
travis.py

feat: add a Chrome based image

---

CHANGELOG.md
README.md
java/Dockerfile.tpl

Will be used for schema spy for instance

Added graphviz to java buildbox

---

CHANGELOG.md
php/Dockerfile.tpl

Require to use `cweagans/composer-patches` for Drupal projects.

feat(php): add patch package to php container

---

CHANGELOG.md
chrome/Dockerfile

Fixes error:
`Error with google-chrome check`
Fixes warning:
`[WARNING]: Empty continuation line found in ...`

fix(Dockerfile): Build of Chrome failed

---

.travis.yml
CHANGELOG.md
README.md
java/Dockerfile.tpl
travis.py

feat(java): migrate to adoptopenjdk and drop jdk 10 support

---

.travis.yml
CHANGELOG.md

so the tag reports the real version https://github.com/ekino/docker-buildbox/blob/master/golang/Dockerfile

fix(go): fix version for accurate tag

---

CHANGELOG.md
Pipfile
Pipfile.lock

Fix https://github.com/ekino/docker-buildbox/network/alert/Pipfile/Jinja2/open

chore(security): upgrade jinja version to 2.10.1

---

.gitignore
.travis.yml
CHANGELOG.md
README.md
config.yml
serverless/Dockerfile.j2
travis.py

Allow python3 lambda deployment via serverless in a GitLab CI job

Create Serverless image with python3

---

.gitignore
.travis.yml
CHANGELOG.md
README.md
awslnx-systemd/Dockerfile.j2
config.yml

Image needed for ansible roles testing with molecule ci.

Create amazonlinux2 with systemd image for Ansible CI jobs

---

.travis.yml
CHANGELOG.md
README.md
config.yml
kubectl/Dockerfile

Create kubectl image w/ kubectx, kubens, kube-score for kubernetes deployments

Create kubectl image

---

.travis.yml
CHANGELOG.md
README.md
config.yml
platformsh/Dockerfile
platformsh/install-cli.sh

Docker image with Platform.sh CLI and python3.6.

Platform.sh CLI image

---

README.md

Versions and Testing were moved at the top of the document.

fix(readme): remove duplicates and reorder images

---

.travis.yml
CHANGELOG.md
azure/dockerfile
config.yml

Create an image for Azure deployment with Azure CLI and Terraform

Create Azure CLI w/ terraform image

---

CHANGELOG.md
config.yml
serverless/Dockerfile.j2

Hello, here is a small contrib to add aws-cli in serverless image

feat(serverless): add aws-cli

---

.travis.yml
CHANGELOG.md
config.yml

Removing node 6 support

---

CHANGELOG.md
config.yml

some security fixes and other fixes
https://golang.org/doc/devel/release.html#go1.13

chore(upgrade): upgrade golang version to 1.13.3

---

CHANGELOG.md
config.yml

Upgrade PHP and its utilities to the latest versions

chore(upgrade): Upgrade to PHP 7.3.10 / 7.2.23

---

config.yml
src/config.py

Here is my code linked to #182 . Format of image renaming is open to discussion.

Change image naming policy to create a repo per image

---

.travis.yml
CHANGELOG.md
config.yml
php/Dockerfile.j2

feat(entity): Add PHP image 7.4

---

CHANGELOG.md
config.yml

all good: 
```bash
(docker-buildbox) ➜  docker-buildbox git:(chore/upgrade) ✗ python travis.py build --image golang --version 1.13                                       
> [Info] Gathering env variables
> [Info] Building: ekino/ci-golang:1.13-latest
Build successful
> [Info] Testing ekino/ci-golang:1.13-latest
Tests successful
(docker-buildbox) ➜  docker-buildbox git:(chore/upgrade) ✗ docker run  ekino/ci-golang:1.13-latest bash -c "go version"
go version go1.13.5 linux/amd64
```

chore(upgrade): upgrade golang (1.13.5)

---

serverless/Dockerfile.j2

Issue and workaround are described here: https://github.com/nodejs/docker-node/issues/813#issuecomment-407339011

fix(serverless): use workaround to fix build issue

---

CHANGELOG.md
java/Dockerfile.j2

feat(java): remove subversion and mercurial

---

CHANGELOG.md
config.yml

Hello! image build ok
```bash
(docker-buildbox) ➜  docker-buildbox git:(chore/upgrade) docker run  ekino/ci-golang:1.13-latest bash -c "go version"                       
go version go1.13.6 linux/amd64
```

chore(upgrade): upgrade golang (1.13.6)

---

CHANGELOG.md
config.yml

Here is a little upgrade fo Go image (crypto lib fixes https://github.com/golang/go/issues?q=milestone%3AGo1.13.7+label%3ACherryPickApproved)

 chore(upgrade): upgrade golang (1.13.7)

---

.travis.yml
CHANGELOG.md
config.yml

once again a minor upgrade https://github.com/golang/go/issues?q=milestone%3AGo1.13.8+label%3ACherryPickApproved
Edit: no minor :p https://golang.org/doc/go1.14

 chore(upgrade): upgrade golang (1.14)

---

CHANGELOG.md
README.md
config.yml
ibm/Dockerfile.j2

Had to install a few ibmcloud cli plugins and install Null provider for terraform

Install Null provider in IBM image

---

CHANGELOG.md
config.yml

Upgrade provider to 1.2.4 for fixes and new resources management

IBM: Upgrade provider version to 1.2.4

---

.github/workflows/build.yml
CHANGELOG.md
config.yml
dind/Dockerfile

@Mallear , maybe if you can do some test on azure ...

chore: rename dind-aws to dind-provider-cli, and add other provider (ibm, azure)

---

CHANGELOG.md
config.yml
kubectl/Dockerfile

Add HELM cli in kubectl image to install charts

Add Helm cli in kubectl image

---

CHANGELOG.md
README.md
config.yml
golang/Dockerfile.j2

https://golang.org/doc/devel/release.html#go1.14
I brought back some tools for CI and dev

chore(upgrade): upgrade golang (1.14.3) and add tools

---

CHANGELOG.md
php/Dockerfile.j2

I m targeting this branch to add the following libraries into the php image: `libcrypto1.1` `libssl1.1`.

chore(php): Add two new libraries into the php image

---

.github/workflows/build.yml
.gitignore
CHANGELOG.md
README.md
config.yml
tezosqa/Dockerfile.j2

Hello I propose to add this image for Tezos blockchain
did not add config test because the added programs do not have option to display version, but tested locally, everything ok

feat(tezos): add tezos image for qa

---

CHANGELOG.md
aws/Dockerfile.j2
chrome/Dockerfile
config.yml
dind/Dockerfile
node/Dockerfile

`make` was missing from the AWS image and [Taskfile](https://taskfile.dev) is a pretty good and simple task runner I would like to include in the images I use.
fixes #304

feat: add make and Taskfile

---

README.md

fix(readme): fix readme for dind

---

CHANGELOG.md
aws/Dockerfile.j2
config.yml

Previously added with:
https://github.com/ekino/docker-buildbox/commit/ef6fb78d525fac9c8ef55cc6811e47236e2d4703#diff-ac68bbf921d953d1cfab916cb6120864
Removed since:
https://github.com/ekino/docker-buildbox/commit/642e8bee4b3b7f560eedd07bbfc30ee1573ab134#diff-ac68bbf921d953d1cfab916cb6120864

Add rsync to aws image

---

CHANGELOG.md
config.yml
tezosqa/Dockerfile.j2

Fixes the smartpy version to avoid surprises in the future :)

fix(tezosqa): smartpy version

---

.github/workflows/build.yml

Only humans need the CI on push.

feat(ci): do not build on push for bots

---

.github/workflows/build.yml
CHANGELOG.md
bitcoind/config.yml

Updating version of bitcoin image

chore(deps): bump bitcoin from 0.20.0 to 0.21.1 in /bitcoin

---

.github/workflows/build.yml

ci(build): disable fail-fast

---

CHANGELOG.md
azure/requirements.txt
dind/requirements.txt
terraform/requirements.txt

chore(azure): bump azure-cli to 2.28.1

---

CHANGELOG.md
java/17/Dockerfile
java/8/Dockerfile
java/config.yml
java/run.sh

Fix https://github.com/ekino/docker-buildbox/issues/500 and https://github.com/ekino/docker-buildbox/issues/548

feat: add new java 17 image

---

CHANGELOG.md
java/11/Dockerfile
java/17/Dockerfile

Fix https://github.com/ekino/docker-buildbox/issues/667

chore: upgrade Java 11 to 11.0.14 and 17 to 17.0.2

---

CHANGELOG.md
node/config.yml

Node: dropping support for NodeJs 12

---

CHANGELOG.md
bitcoind/Dockerfile
bitcoind/config.yml

* Bitcoind : Updating to bitcoind to 23.0
* Bitcoind : Build arm64 image

[Bitcoind] Feat : Build bitcoind docker image arm64 and update to 23.0

---

CHANGELOG.md
aws/Dockerfile
aws/config.yml

* AWS : Build arm64 docker image

[AWS] Feat : Build AWS arm64  docker image

---

CHANGELOG.md
node/Dockerfile
node/config.yml

**Impovements**
* Node : build arm64 docker image

[Node] feat : build arm64 docker image

---

CHANGELOG.md
java/11/Dockerfile
java/17/Dockerfile
java/config.yml
java/run.sh

**Impovements** 
* Java : build arm64 docker image

[Java] feat : build arm64 docker image

---

CHANGELOG.md
cloudsploit/Dockerfile
cloudsploit/config.yml

* Cloudsploit : build arm64 docker image

[Cloudsploit] Feat : build cloudsploit arm64 docker image

---

CHANGELOG.md
chrome/config.yml

* Chrome : build arm64 docker image

[Chrome] Feat : build chrome arm64 docker image

---

CHANGELOG.md
awslnx-systemd/config.yml

* Awslnx-systemd : build arm64 docker image

[Awslnx-systemd] Build awslnx-systemd arm64 docker image

---

CHANGELOG.md
ansible/Dockerfile
ansible/config.yml

* Ansible : Build arm64 docker image

[Ansible] Feat : Build arm64 ansible docker image

---

CHANGELOG.md
php/7.4/Dockerfile
php/8.0/Dockerfile
php/8.1/Dockerfile
php/config.yml
php/run.sh

ping @Bonnai2112 
continue this MR (https://github.com/ekino/docker-buildbox/pull/887) on PHP multi arch
don't hesitate to close this MR if you wish to integrate the changes in your original MR.
- define TARGETARCH variable to be correctly used in the run.sh to install the blackfire PHP extension
- add missing  "AS base" for 8.0 and 8.1 versions

[PHP] feat: build arm64 docker image

---

CHANGELOG.md
node/Dockerfile

This adds "jq" command in node image.

feat(node): add jq command in node dockerfile

---

CHANGELOG.md
aws/Dockerfile
azure/Dockerfile

Add yq bin for parsing yaml files

Add yq bin for parsing yaml files

---

php/config.yml

See https://github.com/ekino/docker-buildbox/actions/runs/5709492421/job/15468393816

fix(php): bump musl from 1.2.4-r0 to 1.2.4-r1

---

CHANGELOG.md
tezosqa/Dockerfile
tezosqa/config.yml

* fix pytezos installation
* refactoring dockerfile 
* update docker in docker (dind) version

fix(tezosqa): fix pytezos installation

---

CHANGELOG.md
php/8.1/Dockerfile

Add a new docker-php-ext and a alpine package into PHP 8.1 image

chore(php8.1): Add new ext

---

README.md

This reverts commit e69064c2113c44f27cbdda92d4e5f489fd84766a.

Revert "chore: updating documentation"
